$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot

function Read-RepoFile([string]$relative) {
    $path = Join-Path $repoRoot $relative
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing release file: $relative" }
    return [IO.File]::ReadAllText($path)
}
function Assert-Contains([string]$text, [string]$needle, [string]$name) {
    if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) { throw "FAILED: $name" }
    Write-Host "PASS: $name"
}
function Assert-NotContains([string]$text, [string]$needle, [string]$name) {
    if ($text.IndexOf($needle, [StringComparison]::Ordinal) -ge 0) { throw "FAILED: $name" }
    Write-Host "PASS: $name"
}

$simActions = Read-RepoFile "src\SimActionMenu.cs"
$setup = Read-RepoFile "src\ExpeditionSetupWindow.cs"
$status = Read-RepoFile "src\TravelStatusOverlay.cs"
$coordinator = Read-RepoFile "src\ExpeditionCoordinator.cs"
$plugin = Read-RepoFile "src\ErenshorFollowPlugin.cs"
$aura = Read-RepoFile "src\FollowSuiteAuraProvider.cs"
$route = Read-RepoFile "src\ZoneAtlasRoutePlanner.cs"
$routePolicy = Read-RepoFile "src\ZoneRouteGraphPolicy.cs"
$leader = Read-RepoFile "src\LeaderController.cs"
$follow = Read-RepoFile "src\FollowController.cs"
$layout = Read-RepoFile "src\SimActionMenuLayoutPolicy.cs"
$planner = Read-RepoFile "src\LocalZoneRoutePlanner.cs"
$crossingPolicy = Read-RepoFile "src\ExpeditionCrossingPolicy.cs"
$crossingObserver = Read-RepoFile "src\ZonelineTriggerObserver.cs"
$doGuardPatch = Read-RepoFile "src\ExpeditionDoGuardPatch.cs"
$ownershipPolicy = Read-RepoFile "src\ExpeditionMovementOwnershipPolicy.cs"
$dragGuard = Read-RepoFile "src\FollowUiDragGuard.cs"
$cameraUiPatch = Read-RepoFile "src\FollowCameraUiPatch.cs"
$cameraCompat = Read-RepoFile "src\FollowCameraCompatibility.cs"
$postZoneReadiness = Read-RepoFile "src\PostZoneRouteReadinessPolicy.cs"

Assert-Contains $simActions 'AddAction("Create Expedition"' "Sim Actions exposes Create Expedition"
Assert-Contains $simActions 'ExpeditionSetupWindow.Open' "Create Expedition opens dedicated setup"
Assert-Contains $simActions 'GetProperty("IsAvailable"' "optional Duel integration checks live provider availability"
Assert-Contains $simActions 'apiVersion == 1 && isAvailable' "optional Duel integration requires supported public API version"
Assert-Contains $simActions 'GetMethod("TryChallenge"' "optional Duel integration invokes public TryChallenge"
Assert-NotContains $simActions 'GetMenuDestinations()' "Sim Actions no longer renders adjacent-only destination submenu"
Assert-Contains $setup 'ListReachableRoutes' "setup enumerates multi-zone reachable atlas destinations"
Assert-Contains $setup 'TryStartRouteExact' "Start revalidates exact tracking and current route"
Assert-Contains $route 'allowedFirstHops' "atlas route is constrained by verified live first hops"
Assert-Contains $routePolicy 'BuildTraversalGraph' "atlas adjacency is normalized without hardcoded destinations"
Assert-Contains $layout 'ActionRowHeight = 28f' "Sim Actions uses compact MMO action rows"
Assert-Contains $simActions 'SimActionMenuLayoutPolicy.ResolvePanelHeight' "Sim Actions height is driven by visible action count"
Assert-Contains $simActions 'layout.childControlHeight = true;' "Sim Actions layout group owns row heights instead of default RectTransform heights"
Assert-Contains $simActions 'element.flexibleHeight = 0f;' "Sim Actions rows cannot absorb unused viewport height"
Assert-Contains $simActions 'DiagnosticStatus()' "Sim Actions exposes an explicit custom-vs-native UI diagnostic"
Assert-Contains $plugin 'PluginVersion = "0.6.4"' "Follow release version identifies the RC telemetry/camera candidate"
Assert-Contains $leader 'if (releasePriorState) _leader.FreeFollow();' "expedition releases selected Sim guard/rest posture before travel"
Assert-Contains $leader '_leader.AssignGuardSpot(target);' "expedition assigns the selected Sim travel target"
Assert-Contains $leader 'sim.GetThisNPC()' "expedition resolves the selected Sim native NPC movement owner"
Assert-Contains $leader 'ExpeditionMovementPolicy.Evaluate' "expedition distinguishes movement ownership from route geometry"
Assert-Contains $leader 'ExpeditionMovementOwnershipPolicy.ShouldSuppressDoGuard' "expedition has an explicit narrow vanilla DoGuard ownership gate"
Assert-Contains $leader 'MyStats.actualRunSpeed' "movement adapter selects the leader native run speed"
Assert-Contains $leader 'animator.SetBool("Walking", walking)' "locomotion animation follows actual movement evidence"
Assert-Contains $leader 'animator.SetBool("Patrol", false)' "expedition locomotion never leaves patrol animation asserted"
Assert-Contains $doGuardPatch '[HarmonyPatch(typeof(SimPlayer), "DoGuard")]' "exact native SimPlayer.DoGuard method is patched"
Assert-Contains $doGuardPatch 'LeaderController.ShouldSuppressNativeDoGuard' "DoGuard patch delegates to exact expedition ownership policy"
Assert-Contains $doGuardPatch 'return true;' "uncertain DoGuard ownership fails open to vanilla"
Assert-Contains $ownershipPolicy '!input.Combat && !input.ExplicitHold && !input.Regrouping && !input.Paused' "DoGuard suppression excludes combat/hold/regroup/pause"
Assert-Contains $ownershipPolicy '!input.TerminalCleanup && !input.CrossingHandoff && !input.NativeZoning' "DoGuard suppression excludes cleanup/crossing/zoning"
Assert-NotContains $leader 'GameData.SimPlayerGrouping.GroupFollow' "expedition never issues a group-wide Follow order"
Assert-Contains $planner 'collider.ClosestPoint(point)' "crossing distance uses true collider shape before bounds fallback"
Assert-Contains $planner 'BuildCrossingTraversalTargets' "planner builds bounded native crossing traversal targets"
Assert-Contains $planner 'PathIntersectsTrigger' "crossing target must prove a path through the live trigger"
Assert-Contains $leader 'ExpeditionCrossingPolicy.Evaluate' "crossing attempts are governed by a bounded pure policy"
Assert-Contains $leader 'crossing_attempt_started' "crossing attempt phase is logged once at phase boundary"
Assert-Contains $leader 'crossing_trigger_entered' "native trigger entry is observed for exact expedition actors"
Assert-Contains $leader 'all pre-built route candidates failed; performing one bounded live re-sample' "all failed geometry candidates get one bounded live re-sample"
Assert-Contains $leader 'BeginExpeditionCrossingHandoff' "leader-first native zoning preserves a bounded player crossing handoff"
Assert-Contains $follow 'internal static bool BeginExpeditionCrossingHandoff' "Follow exposes only the bounded already-proven crossing handoff"
Assert-Contains $follow 'crossingHandoff ? 0.20f : StopDistance' "crossing handoff does not stop at ordinary three-meter follow distance"
Assert-Contains $crossingObserver '[HarmonyPatch(typeof(Zoneline), "OnTriggerEnter")]' "read-only native Zoneline trigger observer is installed"
Assert-Contains $crossingObserver 'LeaderController.NoteNativeZonelineTrigger' "trigger observer forwards observations without zoning itself"
Assert-Contains $crossingPolicy 'MaximumAttempts = 2' "crossing retry count is bounded"
Assert-Contains $coordinator 'ExpeditionDestinationResolver.Resolve(route[1]' "current first leg is resolved through live Zoneline authority"
Assert-Contains $coordinator 'SimTrackingRebind.AvatarMatchesTracking' "exact persistent Sim identity is enforced"
Assert-Contains $coordinator 'ZoneAtlasRoutePlanner.TryBuild(_session.CurrentZone, _session.DestinationName' "route recalculates after each native zone"
Assert-Contains $coordinator 'zone_transition_observed' "coordinator records native transition observation"
Assert-Contains $coordinator 'destination_zone_entered' "coordinator records verified destination-zone entry"
Assert-Contains $coordinator 'leader_reacquired' "coordinator records exact leader reacquisition"
Assert-Contains $coordinator 'next_leg_revalidated' "next expedition leg is revalidated after native zoning"
Assert-Contains $coordinator 'TickPostZoneRouteReadiness' "post-zone next leg waits for fresh route readiness evidence"
Assert-Contains $coordinator 'fresh-zoneline-and-navmesh-probe' "post-zone readiness never uses a blind sleep"
Assert-Contains $postZoneReadiness 'TimeoutSeconds = 8.0f' "post-zone route readiness has a bounded timeout"
Assert-Contains $postZoneReadiness 'MaximumAttempts = 16' "post-zone route readiness has a bounded retry count"
Assert-Contains $status 'Changing zones...  Reacquiring' "status reports native zoning/reacquisition"
Assert-Contains $status 'ExpeditionCoordinator.Pause' "status Pause uses coordinator"
Assert-Contains $status 'ExpeditionCoordinator.Resume' "status Resume uses coordinator"
Assert-Contains $status 'ExpeditionCoordinator.Cancel' "status Cancel is explicit"
Assert-NotContains $status 'HideExpeditionStatus();\r\n                    ExpeditionCoordinator.Cancel' "window close is not coupled to cancel"
Assert-Contains $status 'CampmasterIntegrationBridge.TryDeclareHere' "Camp Here remains capability-backed"
Assert-Contains $status 'ExpeditionCoordinator.TryReturn' "verified arrival can initiate Return"
Assert-Contains $plugin 'TravelStatusOverlay.Tick();' "status continues rendering through native zoning lifecycle"
Assert-Contains $plugin 'ExpeditionSetupWindow.DisposeForLifecycle();' "plugin unload destroys setup UI"
Assert-Contains $plugin 'TravelStatusOverlay.ResetForLifecycle();' "plugin unload destroys status UI"
Assert-Contains $plugin 'ExpeditionCoordinator.Shutdown();' "plugin unload cancels/clears expedition runtime"
Assert-Contains $dragGuard 'eventData.button != PointerEventData.InputButton.Left' "Follow retained drag gestures are left-button only"
Assert-Contains $dragGuard 'AcquireOwnership();' "Follow drag ownership begins at pointer-down/begin-drag"
Assert-Contains $dragGuard 'Input.GetMouseButton(0)' "Follow drag ownership releases when the physical left button is gone"
Assert-Contains $dragGuard 'OnApplicationFocus' "Follow drag ownership releases on focus loss"
Assert-Contains $dragGuard 'OnApplicationPause' "Follow drag ownership releases on pause"
Assert-Contains $cameraUiPatch '[HarmonyPatch(typeof(CameraController), "UsingUI")]' "Follow owns a standalone-safe CameraController.UsingUI compatibility patch"
Assert-Contains $cameraUiPatch '!__result && FollowUiDragGuard.OwnsPointerGesture' "camera UI postfix is monotonic and only raises native UI state"
Assert-Contains $doGuardPatch '[HarmonyPrepare]' "DoGuard patch validates exact native method shape before applying"
Assert-Contains $doGuardPatch 'method.ReturnType == typeof(void) && method.GetParameters().Length == 0' "DoGuard patch requires verified zero-argument void shape"
Assert-Contains $cameraUiPatch '[HarmonyPrepare]' "camera UI patch validates the current native boundary before applying"
Assert-Contains $cameraUiPatch 'FollowCameraCompatibility.VerifyUsingUiBoundary' "camera patch delegates to the full runtime compatibility proof"
Assert-Contains $cameraCompat 'UIWindows' "camera compatibility verifies native UIWindows field"
Assert-Contains $cameraCompat 'typeof(List<GameObject>)' "camera compatibility requires UIWindows List<GameObject>"
Assert-Contains $cameraCompat 'activeSelf' "camera compatibility verifies UsingUI activeSelf scan"
Assert-Contains $cameraCompat 'ModernControls' "camera compatibility verifies modern camera path"
Assert-Contains $cameraCompat 'releaseMouse' "camera compatibility verifies modern releaseMouse gate"
Assert-Contains $cameraCompat 'GetAxis' "camera compatibility verifies native mouse-axis use"
Assert-Contains $cameraCompat 'DraggingUIElement' "camera compatibility verifies standard drag flag gate"
Assert-Contains $cameraCompat 'GetILAsByteArray' "camera compatibility inspects current runtime IL rather than trusting a stale token"
Assert-Contains $dragGuard 'End(true);' "pointer-up/end path completes a real Follow drag exactly once"
Assert-Contains $dragGuard 'forgetwhtuno.erenshor.ui.drag.owners.v1' "Follow drag ownership coordinates through the standalone BCL process registry"
Assert-Contains $dragGuard 'forgetwhtuno.erenshor.ui.drag.nativeBaseline.v1' "Follow drag ownership shares the process native-baseline key"
Assert-Contains $dragGuard 'ReleaseProcessOwnership' "Follow release cannot blindly clear another participating mod owner"
Assert-Contains $aura 'FollowUiSurfaceRouter.CloseAllVisuals()' "Suite closePanel closes all Follow visual surfaces without cancelling gameplay"
Assert-Contains $aura 'FollowUiSurfaceRouter.Topmost()' "Suite ui.state advertises top Follow surface"

$productionSource = (Get-ChildItem (Join-Path $repoRoot "src") -Filter *.cs | ForEach-Object { [IO.File]::ReadAllText($_.FullName) }) -join "`n"
Assert-NotContains $productionSource 'SceneChange.ChangeScene(' "Follow never manually loads expedition scenes"
Assert-NotContains $productionSource '.ZoneSim(' "Follow never directly zones a Sim"
Assert-NotContains $productionSource '.TravelToZone(' "Follow never invokes Sim tracking travel authority"
Assert-NotContains $productionSource 'BringSimToPlayer(' "Follow never teleports/reconstructs a Sim through helper authority"
Assert-NotContains $productionSource 'SpawnMeInPlayerZone(' "Follow never forces a Sim spawn into the player zone"
Assert-NotContains $productionSource '.Warp(' "Follow never warps the expedition leader"
Assert-NotContains $productionSource 'transform.position =' "Follow never manually moves the Sim leader transform"
Assert-NotContains $productionSource 'void OnGUI(' "production UI contains no OnGUI"
Write-Host "Erenshor Follow release static tests: ALL PASS" -ForegroundColor Green
